{% set name = "cssselect2" %}
{% set version = "0.2.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 505d2ce3d3a1d390ddb52f7d0864b7efeb115a5b852a91861b498b92424503ab

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - tinycss2
  run:
    - python >={{ python_min }}
    - tinycss2

test:
  requires:
    - python {{ python_min }}
  imports:
    - cssselect2

about:
  home: https://github.com/Kozea/cssselect2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CSS selectors for Python ElementTree
  description: |
    cssselect2 is a straightforward implementation of CSS3 Selectors for markup documents.
  doc_url: http://cssselect2.readthedocs.io
  dev_url: https://github.com/Kozea/cssselect2

extra:
  recipe-maintainers:
    - johanneskoester
