{% set name = "cssselect2" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b5d6dea81a5eb0c9ca39f116c8578dd413778060c94c1f51196371618909325

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
    - tinycss2
  run:
    - python
    - tinycss2

test:
  imports:
    - cssselect2

about:
  home: https://github.com/Kozea/cssselect2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CSS selectors for Python ElementTree
  description: |
    cssselect2 is a straightforward implementation of CSS3 Selectors for markup documents.
  doc_url: http://cssselect2.readthedocs.io
  dev_url: https://github.com/Kozea/cssselect2

extra:
  recipe-maintainers:
    - johanneskoester
