{% set name = "cssselect2" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c2716f06b5de93f701d5755a9666f2ee22cbcd8b4da8adddfc30095ffea3abc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
    - tinycss2
  run:
    - python
    - tinycss2

test:
  imports:
    - cssselect2

about:
  home: https://github.com/Kozea/cssselect2
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: CSS selectors for Python ElementTree
  description: |
    cssselect2 is a straightforward implementation of CSS3 Selectors for markup documents.
  doc_url: http://cssselect2.readthedocs.io
  dev_url: https://github.com/Kozea/cssselect2

extra:
  recipe-maintainers:
    - johanneskoester
